/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daranbookstudio;

import java.awt.HeadlessException;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;

/**
 *
 * @author 雅詩
 */

public class StudioWindow extends javax.swing.JFrame {

    public LoadingWindow loadwin;
    private ArrayList<String> fileNameArray;
    private Boolean isUNIX;
    private DefaultListModel listModel;
    private String dirAddress;
    private String separator;
    private String nowtxtfile;
    
    public String softname = "DaRanBookPackage Studio v1.0 beta";
    /**
     * Creates new form StudioWindow
     */
    public StudioWindow() {
        initComponents();
        loadwin = new LoadingWindow();
        loadwin.closewindow();
        lbl_stat.setText("请新建或打开一个数据包。使用较短的文件路径更容易编辑。");
        this.setTitle(softname + " - 尚未加载数据包文件夹");
        fileNameArray = new ArrayList<String>();
        System.out.println("os.name:"+System.getProperties().getProperty("os.name"));
        separator = System.getProperties().getProperty("file.separator");
        win_filemgr.setTitle(win_filemgr.getTitle() + "：" + System.getProperties().getProperty("os.name") + " 格式");
        win_fileedit.setTitle(win_fileedit.getTitle() + "：" + "没有打开文件，请在左侧列表选择要编辑的txt文件。");
        listModel = new DefaultListModel();
        filemgr_list_files.setModel(listModel);
        //filemgr_list_files.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        filemgr_list_files.addMouseListener(new MouseAdapter() {         
            public void mouseClicked(MouseEvent e) {
//                if (e.getClickCount() == 1) {
//                    oneClick(filemgr_list_files.getSelectedValue());
//                }
                if (e.getClickCount() == 2) {
                    twoClick(filemgr_list_files.getSelectedValue());
                }
            }
        });
    }
    
    public void twoClick(Object value) {
        loadingOpen("正在打开文件");
        String fileAddress = dirAddress + separator + value.toString();
        win_fileedit.setTitle("文件编辑：" + fileAddress);
        nowtxtfile = fileAddress;
        BufferedReader reader;
        if (typeidtxt(fileAddress)) {
            try {
                reader = new BufferedReader(new InputStreamReader(new FileInputStream(fileAddress), "UTF-8")); // 指定读取文件的编码格式，要和写入的格式一致，以免出现中文乱码,
                String str = null;
                while ((str = reader.readLine()) != null) {
                    fileedit_txt_edit.setText(fileedit_txt_edit.getText() + str + "\n");
                }
                reader.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        loadingClose();
    }
    
    private Boolean typeidtxt (String fileAddress) {
        String typename = fileAddress.substring(fileAddress.length()-3);
        if (typename.equals("txt") || typename.equals("TXT")) {
            fileedit_btn_savefile.setEnabled(true);
            fileedit_txt_edit.setEnabled(true);
            fileedit_txt_edit.setText("");
            return true;
        } else {
            fileedit_btn_savefile.setEnabled(false);
            fileedit_txt_edit.setEnabled(false);
            fileedit_txt_edit.setText("不支持的文件格式（" + typename + "），不能编辑。");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        win_filemgr = new javax.swing.JInternalFrame();
        jToolBar1 = new javax.swing.JToolBar();
        filemgr_btn_addfile = new javax.swing.JButton();
        filemgr_btn_removefile = new javax.swing.JButton();
        filemgr_btn_adddir = new javax.swing.JButton();
        filemgr_btn_clear = new javax.swing.JButton();
        filemgr_btn_reload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        filemgr_list_files = new javax.swing.JList();
        jToolBar2 = new javax.swing.JToolBar();
        mainwin_btn_opendir = new javax.swing.JButton();
        mainwin_btn_newdir = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        lbl_stat = new javax.swing.JLabel();
        win_insert = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        index_txt_zipname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        index_txt_author = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        index_txt_press = new javax.swing.JTextField();
        index_btn_gbookinfo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        index_btn_gfilelist = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lst_pic1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton17 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField21 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        lst_pic2 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        win_fileedit = new javax.swing.JInternalFrame();
        jToolBar3 = new javax.swing.JToolBar();
        fileedit_btn_savefile = new javax.swing.JButton();
        fileedit_btn_clear = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        fileedit_txt_newfilename = new javax.swing.JTextField();
        fileedit_btn_newfile = new javax.swing.JButton();
        fileedit_btn_savenew = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        fileedit_chk_entermode = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileedit_txt_edit = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        win_filemgr.setTitle("文件管理器");
        win_filemgr.setVisible(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        filemgr_btn_addfile.setText("添加");
        filemgr_btn_addfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filemgr_btn_addfile.setFocusable(false);
        filemgr_btn_addfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filemgr_btn_addfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        filemgr_btn_addfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filemgr_btn_addfileActionPerformed(evt);
            }
        });
        jToolBar1.add(filemgr_btn_addfile);

        filemgr_btn_removefile.setText("删除");
        filemgr_btn_removefile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filemgr_btn_removefile.setFocusable(false);
        filemgr_btn_removefile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filemgr_btn_removefile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(filemgr_btn_removefile);

        filemgr_btn_adddir.setText("添加文件夹");
        filemgr_btn_adddir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filemgr_btn_adddir.setFocusable(false);
        filemgr_btn_adddir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filemgr_btn_adddir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(filemgr_btn_adddir);

        filemgr_btn_clear.setText("清空");
        filemgr_btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filemgr_btn_clear.setFocusable(false);
        filemgr_btn_clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filemgr_btn_clear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(filemgr_btn_clear);

        filemgr_btn_reload.setText("刷新");
        filemgr_btn_reload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filemgr_btn_reload.setFocusable(false);
        filemgr_btn_reload.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        filemgr_btn_reload.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(filemgr_btn_reload);

        jScrollPane1.setViewportView(filemgr_list_files);

        javax.swing.GroupLayout win_filemgrLayout = new javax.swing.GroupLayout(win_filemgr.getContentPane());
        win_filemgr.getContentPane().setLayout(win_filemgrLayout);
        win_filemgrLayout.setHorizontalGroup(
            win_filemgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        win_filemgrLayout.setVerticalGroup(
            win_filemgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(win_filemgrLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jToolBar2.setFloatable(false);

        mainwin_btn_opendir.setText("打开数据包文件夹");
        mainwin_btn_opendir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainwin_btn_opendir.setFocusable(false);
        mainwin_btn_opendir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainwin_btn_opendir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainwin_btn_opendir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainwin_btn_opendirActionPerformed(evt);
            }
        });
        jToolBar2.add(mainwin_btn_opendir);

        mainwin_btn_newdir.setText("新建数据包文件夹");
        mainwin_btn_newdir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainwin_btn_newdir.setFocusable(false);
        mainwin_btn_newdir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainwin_btn_newdir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(mainwin_btn_newdir);
        jToolBar2.add(filler1);

        lbl_stat.setText("就绪。");
        jToolBar2.add(lbl_stat);

        win_insert.setTitle("插入条目");
        win_insert.setVisible(true);

        jLabel4.setText("数据包（压缩包）名称（全部为小写英文字母不包含标点）：");

        index_txt_zipname.setText("pingmiangoucheng");

        jLabel7.setText("书籍编者（如果有多个编者请用空格隔开）：");

        index_txt_author.setText("xxx xxx xxx");

        jLabel8.setText("出版社名称：");

        index_txt_press.setText("xxxxxx出版社");

        index_btn_gbookinfo.setText("↓ 插入书籍信息 ↓");
        index_btn_gbookinfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<html>\n书籍信息必须在文件的前三行并且不能修改顺序，<p>\n请先插入书籍信息再插入文件列表。\n</html>");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html>\n将生成一个文件列表。<p>\n请注意章节的pdf和txt应由小到大排序，错误的章节顺序会导致显示问题。<p>\n生成后请手工核对一下排序，并删除无关文件。<p>\n</html>");
        jLabel10.setToolTipText("");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        index_btn_gfilelist.setText("↓ 插入文件列表 ↓");
        index_btn_gfilelist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(index_txt_zipname)
                    .addComponent(index_txt_author)
                    .addComponent(index_txt_press)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(index_btn_gbookinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .addComponent(index_btn_gfilelist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(index_txt_zipname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(index_txt_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(index_txt_press, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(index_btn_gbookinfo)
                    .addComponent(index_btn_gfilelist))
                .addContainerGap())
        );

        jTabbedPane1.addTab("引导文件生成", jPanel1);

        jLabel1.setText("自定义章名称（如果不是第一小节请不要修改）：");

        jTextField1.setText("第？章 xxxxx");
        jTextField1.setEnabled(false);

        jCheckBox1.setText("这是本章的第一节");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setText("自定义节名称：");

        jTextField2.setText("第？节 xxxxx");

        jLabel5.setText("章号（纯数字）：");

        jTextField3.setText("0");

        jLabel6.setText("节号（纯数字）：");

        jTextField4.setText("2");

        jButton10.setText("↓ 插入章节名称信息 ↓");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(0, 572, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("章节名称生成", jPanel2);

        jLabel11.setText("图片文件名：");

        lst_pic1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setText("图片标题：");

        jTextField8.setText("未命名图片");

        jLabel13.setText("图片描述：");

        jTextField9.setText("这个图片没有介绍");

        jButton13.setText("↓ 添加一张图片到相册 ↓");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lst_pic1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField8)
                    .addComponent(jTextField9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lst_pic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("相册图片列表生成", jPanel3);

        jLabel14.setText("关键字：");

        jTextField10.setText("关键字");

        jLabel15.setText("解释：");

        jTextField11.setText("这是关键字");

        jButton15.setText("↓ 插入关键字信息 ↓");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField11)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))
                        .addGap(0, 740, Short.MAX_VALUE))
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("关键字解释生成", jPanel4);

        jLabel16.setText("选择题配置文件中第一行必须为题目组名称：");

        jTextField12.setText("未命名选择题组");

        jButton16.setText("↓ 插入选择题组名称 ↓");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel17.setText("请在下面逐个添加选择题题目：");

        jLabel18.setText("题目：");

        jTextField13.setText("1.问题？");

        jLabel19.setText("选项A：");

        jTextField14.setText("A.");

        jLabel20.setText("选项B：");

        jTextField15.setText("B.");

        jLabel21.setText("选项C：");

        jTextField16.setText("C.");

        jTextField17.setText("D.");

        jLabel22.setText("选项D：");

        jLabel23.setText("正确的选项是：");

        jCheckBox2.setSelected(true);
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jCheckBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton17.setText("↓ 插入一个题目 ↓");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField14))
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField13))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox4)
                                        .addComponent(jCheckBox3)
                                        .addComponent(jCheckBox5))
                                    .addComponent(jCheckBox2))
                                .addGap(51, 51, 51)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("选择题生成", jPanel5);

        jLabel24.setText("分类题配置文件中第一行必须为题目：");

        jTextField18.setText("未命名分类题");

        jButton18.setText("↓ 插入分类题名称 ↓");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel25.setText("注意，一共只能添加两个分类，每个分类有四张图片！");

        jLabel26.setText("分类A名称：");

        jTextField19.setText("分类A");

        jLabel27.setText("分类B名称：");

        jTextField20.setText("分类B");

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("分类A");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jRadioButton2.setText("分类B");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField21.setText("未命名图片");

        jLabel28.setText("图片名：");

        lst_pic2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel29.setText("图片文件名：");

        jButton19.setText("↓ 插入一张图片 ↓");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel30.setText("加入图片：");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField18)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(lst_pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel30))
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lst_pic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("分类题生成", jPanel6);

        jLabel31.setText("此功能暂时不可用");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(784, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("资料包打包和加密", jPanel7);

        javax.swing.GroupLayout win_insertLayout = new javax.swing.GroupLayout(win_insert.getContentPane());
        win_insert.getContentPane().setLayout(win_insertLayout);
        win_insertLayout.setHorizontalGroup(
            win_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        win_insertLayout.setVerticalGroup(
            win_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        win_fileedit.setTitle("文件编辑");
        win_fileedit.setVisible(true);

        jToolBar3.setRollover(true);

        fileedit_btn_savefile.setText("保存修改");
        fileedit_btn_savefile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fileedit_btn_savefile.setEnabled(false);
        fileedit_btn_savefile.setFocusable(false);
        fileedit_btn_savefile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileedit_btn_savefile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        fileedit_btn_savefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileedit_btn_savefileActionPerformed(evt);
            }
        });
        jToolBar3.add(fileedit_btn_savefile);

        fileedit_btn_clear.setText("清空");
        fileedit_btn_clear.setFocusable(false);
        fileedit_btn_clear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileedit_btn_clear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(fileedit_btn_clear);

        jLabel33.setText("新建文件名:");
        jToolBar3.add(jLabel33);

        fileedit_txt_newfilename.setText("新建配置文件.txt");
        jToolBar3.add(fileedit_txt_newfilename);

        fileedit_btn_newfile.setText("新建文件");
        fileedit_btn_newfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fileedit_btn_newfile.setFocusable(false);
        fileedit_btn_newfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileedit_btn_newfile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(fileedit_btn_newfile);

        fileedit_btn_savenew.setText("存为新文件");
        fileedit_btn_savenew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fileedit_btn_savenew.setFocusable(false);
        fileedit_btn_savenew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileedit_btn_savenew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(fileedit_btn_savenew);
        jToolBar3.add(filler2);

        fileedit_chk_entermode.setSelected(true);
        fileedit_chk_entermode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fileedit_chk_entermode.setFocusable(false);
        fileedit_chk_entermode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fileedit_chk_entermode.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(fileedit_chk_entermode);

        jLabel32.setText("强制UNIX风格换行符");
        jToolBar3.add(jLabel32);

        jCheckBox7.setSelected(true);
        jCheckBox7.setEnabled(false);
        jCheckBox7.setFocusable(false);
        jCheckBox7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jCheckBox7);

        jLabel2.setText("强制使用UTF-8读写");
        jToolBar3.add(jLabel2);

        fileedit_txt_edit.setEnabled(false);
        jScrollPane2.setViewportView(fileedit_txt_edit);

        javax.swing.GroupLayout win_fileeditLayout = new javax.swing.GroupLayout(win_fileedit.getContentPane());
        win_fileedit.getContentPane().setLayout(win_fileeditLayout);
        win_fileeditLayout.setHorizontalGroup(
            win_fileeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        win_fileeditLayout.setVerticalGroup(
            win_fileeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(win_fileeditLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(win_filemgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(win_insert)
                    .addComponent(win_fileedit)))
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(win_insert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(win_fileedit))
                    .addComponent(win_filemgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void filemgr_btn_addfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filemgr_btn_addfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filemgr_btn_addfileActionPerformed

    private void mainwin_btn_opendirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainwin_btn_opendirActionPerformed
        loadingOpen("正在统计文件");
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);//只能选择目录
        String path=null;
        int flag = 0;
        File f = null;
        try{     
            flag=fc.showOpenDialog(null);     
        }    
        catch(HeadlessException head){     
             System.out.println("Open File Dialog ERROR!");    
        }        
        if(flag==JFileChooser.APPROVE_OPTION){
             //获得该文件
            f=fc.getSelectedFile();    
            path=f.getPath();
         }
        if (path != null && !path.equals("null")) {
            this.setTitle(softname + " - " + path);
            lbl_stat.setText("已挂载文件夹：" + path + "。");
            dirAddress = path;
            list(path, false, false);
        } else {
            lbl_stat.setText("已取消选择。" + path);
        }
        loadingClose();
    }//GEN-LAST:event_mainwin_btn_opendirActionPerformed

    private void convertEnter() {
        if (fileedit_chk_entermode.isSelected()) {
            fileedit_txt_edit.setText(fileedit_txt_edit.getText().replaceAll("\r\n", "\n"));
        }
    }
    
    private void fileedit_btn_savefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileedit_btn_savefileActionPerformed
        loadingOpen("正在保存");
        BufferedWriter fw = null;
        convertEnter();
        try {
            File file = new File(nowtxtfile);
            fw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file, false), "UTF-8")); // 指定编码格式，以免读取时中文字符异常
            fw.append(fileedit_txt_edit.getText());
            //fw.newLine();
            fw.flush(); // 全部写入缓存中的内容
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (fw != null) {
                try {
                    fw.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        loadingClose();
    }//GEN-LAST:event_fileedit_btn_savefileActionPerformed

    private ArrayList<String> list(String filePath, boolean b_cdir, boolean b_dirname) {
        listModel.removeAllElements();
        ArrayList<String> filelist = new ArrayList<String>();
        String[] arr = null;
            File root = new File(filePath);
            File[] files = root.listFiles();
            for(File file:files){
                if(file.isDirectory()){
                    if (b_cdir) {
                        list(file.getAbsolutePath(), b_cdir, b_dirname);
                    }
                    if (b_dirname) {
                        System.out.println(file.getName());
                        filelist.add(file.getName());
                        //mw.setNum(false);
                        addListItem(file.getName());
                    }
                } else {
                    System.out.println(file.getName());
                    filelist.add(file.getName());
                    //mw.setNum(false);
                    addListItem(file.getName());
                }
            }
        return filelist;
    }
    private void addListItem(String filename) {
        listModel.addElement(filename);
    }
    
    private void loadingOpen(String info) {
        this.setEnabled(false);
        loadwin.openwindow(info);
    }
    private void loadingClose() {
        this.setEnabled(true);
        this.requestFocus();
        loadwin.closewindow();
        
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudioWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileedit_btn_clear;
    private javax.swing.JButton fileedit_btn_newfile;
    private javax.swing.JButton fileedit_btn_savefile;
    private javax.swing.JButton fileedit_btn_savenew;
    private javax.swing.JCheckBox fileedit_chk_entermode;
    private javax.swing.JTextPane fileedit_txt_edit;
    private javax.swing.JTextField fileedit_txt_newfilename;
    private javax.swing.JButton filemgr_btn_adddir;
    private javax.swing.JButton filemgr_btn_addfile;
    private javax.swing.JButton filemgr_btn_clear;
    private javax.swing.JButton filemgr_btn_reload;
    private javax.swing.JButton filemgr_btn_removefile;
    private javax.swing.JList filemgr_list_files;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton index_btn_gbookinfo;
    private javax.swing.JButton index_btn_gfilelist;
    private javax.swing.JTextField index_txt_author;
    private javax.swing.JTextField index_txt_press;
    private javax.swing.JTextField index_txt_zipname;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lbl_stat;
    private javax.swing.JComboBox lst_pic1;
    private javax.swing.JComboBox lst_pic2;
    private javax.swing.JButton mainwin_btn_newdir;
    private javax.swing.JButton mainwin_btn_opendir;
    private javax.swing.JInternalFrame win_fileedit;
    private javax.swing.JInternalFrame win_filemgr;
    private javax.swing.JInternalFrame win_insert;
    // End of variables declaration//GEN-END:variables
}
